---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "kube-node-tuning.labels" . | indent 4 }}
data:
  99-kube-node-tuning.conf: |-
    {{ index .Values "configmap" "sysctl-conf" | nindent 4 }}
  setup.sh: |-
    {{ index .Values "configmap" "setup-sh" | nindent 4 }}
