apiVersion: v1
kind: Namespace
metadata:
  name: kube-node-tunning

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sysctl-config
  namespace: kube-node-tunning
data:
  99-kube-node-tunning.conf: |-
    kernel.pid_max=131072
    net.netfilter.nf_conntrack_max=1048576
    fs.inotify.max_user_watches=65536

    net.ipv4.neigh.default.gc_thresh1=8192
    net.ipv4.neigh.default.gc_thresh2=32768
    net.ipv4.neigh.default.gc_thresh3=65536
    net.ipv6.neigh.default.gc_thresh1=8192
    net.ipv6.neigh.default.gc_thresh2=32768
    net.ipv6.neigh.default.gc_thresh3=65536
  setup.sh: |-
    #!/bin/sh
    set -ex
    cp 99-kube-node-tunning.conf /etc/sysctl.d
    sysctl -p /etc/sysctl.d/99-kube-node-tunning.conf
    # cat 99-kube-node-tunning.conf
    sleep infinity
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-tunning
  namespace: kube-node-tunning
  labels:
    app: kube-node-tunning
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-node-tunning
  template:
    metadata:
      labels:
        app: kube-node-tunning
    spec:
      containers:
        - name: kube-node-tunning
          image: docker.m.daocloud.io/alpine
          command:
            - /bin/sh
            - setup.sh
          workingDir: /opt/kube-node-tunning
          # command:
          #   - sleep
          #   - infinity
          volumeMounts:
            - name: sysctl-config-volume
              mountPath: /opt/kube-node-tunning
            - name: sysctl-dir
              mountPath: /etc/sysctl.d
          securityContext:
            privileged: true
            runAsUser: 0
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      volumes:
        - name: sysctl-config-volume
          configMap:
            name: sysctl-config
        - name: sysctl-dir
          hostPath:
            path: /etc/sysctl.d
            type: ""
      terminationGracePeriodSeconds: 0
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
