---
apiVersion: v2
description: |
  kube-node-tuning is aimed at kernel tuning by kubernetes.
  It's useful to High performance application, Large Scale Cluster, Network Tuning.
home: https://github.com/kubean-io/kube-node-tuning
icon: https://raw.githubusercontent.com/kubean-io/kube-node-tuning/main/charts/icon.png
keywords:
  - tuning
  - sysctl
name: kube-node-tuning
sources:
  - https://github.com/kubean-io/kube-node-tuning
appVersion: 0.3.1
version: 0.3.1
