---
name: Tests
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.8"
      - run: |
          make test
